# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.zdist_lpdf <- function(x, mu, sigma, a, b) {
    .Call(`_zcurve_zdist_lpdf`, x, mu, sigma, a, b)
}

.tdist_lpdf <- function(x, mu, df, a, b) {
    .Call(`_zcurve_tdist_lpdf`, x, mu, df, a, b)
}

.zdist_pdf <- function(x, mu, sigma, a, b) {
    .Call(`_zcurve_zdist_pdf`, x, mu, sigma, a, b)
}

.zdist_cens_lpdf <- function(lb, ub, mu, sigma, a, b) {
    .Call(`_zcurve_zdist_cens_lpdf`, lb, ub, mu, sigma, a, b)
}

.tdist_pdf <- function(x, mu, df, a, b) {
    .Call(`_zcurve_tdist_pdf`, x, mu, df, a, b)
}

.dirichlet_rng <- function(alpha) {
    .Call(`_zcurve_dirichlet_rng`, alpha)
}

.zcurve_EM_fit_RCpp <- function(x, type, mu, sigma, theta, a, b, sig_level, max_iter, criterion) {
    .Call(`_zcurve_zcurve_EM_fit_RCpp`, x, type, mu, sigma, theta, a, b, sig_level, max_iter, criterion)
}

.zcurve_EM_fit_fast_RCpp <- function(x, mu, sigma, theta, a, b, sig_level, max_iter, criterion) {
    .Call(`_zcurve_zcurve_EM_fit_fast_RCpp`, x, mu, sigma, theta, a, b, sig_level, max_iter, criterion)
}

.zcurve_EMc_fit_fast_RCpp <- function(x, lb, ub, mu, sigma, theta, a, b, sig_level, max_iter, criterion) {
    .Call(`_zcurve_zcurve_EMc_fit_fast_RCpp`, x, lb, ub, mu, sigma, theta, a, b, sig_level, max_iter, criterion)
}

.zcurve_EMc_fit_fast_w_RCpp <- function(x, x_w, lb, ub, b_w, mu, sigma, theta, a, b, sig_level, max_iter, criterion) {
    .Call(`_zcurve_zcurve_EMc_fit_fast_w_RCpp`, x, x_w, lb, ub, b_w, mu, sigma, theta, a, b, sig_level, max_iter, criterion)
}

.zcurve_EM_start_RCpp <- function(x, type, K, mu, sigma, mu_alpha, mu_max, theta_alpha, a, b, sig_level, fit_reps, max_iter, criterion) {
    .Call(`_zcurve_zcurve_EM_start_RCpp`, x, type, K, mu, sigma, mu_alpha, mu_max, theta_alpha, a, b, sig_level, fit_reps, max_iter, criterion)
}

.zcurve_EM_boot_RCpp <- function(x, type, mu, sigma, theta, a, b, sig_level, bootstrap, max_iter, criterion) {
    .Call(`_zcurve_zcurve_EM_boot_RCpp`, x, type, mu, sigma, theta, a, b, sig_level, bootstrap, max_iter, criterion)
}

.zcurve_EM_start_fast_RCpp <- function(x, K, mu, sigma, mu_alpha, mu_max, theta_alpha, a, b, sig_level, fit_reps, max_iter, criterion) {
    .Call(`_zcurve_zcurve_EM_start_fast_RCpp`, x, K, mu, sigma, mu_alpha, mu_max, theta_alpha, a, b, sig_level, fit_reps, max_iter, criterion)
}

.zcurve_EM_boot_fast_RCpp <- function(x, mu, sigma, theta, a, b, sig_level, bootstrap, max_iter, criterion) {
    .Call(`_zcurve_zcurve_EM_boot_fast_RCpp`, x, mu, sigma, theta, a, b, sig_level, bootstrap, max_iter, criterion)
}

.zcurve_EMc_start_fast_RCpp <- function(x, lb, ub, K, mu, sigma, mu_alpha, mu_max, theta_alpha, a, b, sig_level, fit_reps, max_iter, criterion) {
    .Call(`_zcurve_zcurve_EMc_start_fast_RCpp`, x, lb, ub, K, mu, sigma, mu_alpha, mu_max, theta_alpha, a, b, sig_level, fit_reps, max_iter, criterion)
}

.zcurve_EMc_boot_fast_RCpp <- function(x, lb, ub, indx, mu, sigma, theta, a, b, sig_level, bootstrap, max_iter, criterion) {
    .Call(`_zcurve_zcurve_EMc_boot_fast_RCpp`, x, lb, ub, indx, mu, sigma, theta, a, b, sig_level, bootstrap, max_iter, criterion)
}

.zcurve_EMc_boot_fast_w_RCpp <- function(x, x_w, lb, ub, b_w, indx, mu, sigma, theta, a, b, sig_level, bootstrap, max_iter, criterion) {
    .Call(`_zcurve_zcurve_EMc_boot_fast_w_RCpp`, x, x_w, lb, ub, b_w, indx, mu, sigma, theta, a, b, sig_level, bootstrap, max_iter, criterion)
}

